package main

import (
	"fmt"
	"github.com/Paskual86/hackerrank-go.git/pkg/algorithms"
)

func main() {
	// TGATGCCGTCCCCTCAACTTGAGTGCTCCTAATGCGTTGC
	// GAAATAAA
	// TGATGCCGTCCCCTCAACTTGAGTGCTCCTAATGCGTTGCTGATGCCGTCCCCTCAACTTGAGTGCTCCTAATGCGTTGCTGATGCCGTCCCCTCAACTTGAGTGCTCCTAATGCGTTGCTGATGCCGTCCCCTCAACTTGAGTGCTCCTAATGCGTTGCTGATGCCGTCCCCTCAACTTGAGTGCTCCTAATGCGTTGCTGATGCCGTCCCCTCAACTTGAGTGCTCCTAATGCGTTGC
	fmt.Printf("Min Substring: %d \n", algorithms.SteadyGene("TGATGCCGTCCCCTCAACTTGAGTGCTCCTAATGCGTTGC")) //TGATGCCGTCCCCTCAACTTGAGTGCTCCTAATGCGTTGC
}
